### ISSUE TITLE
Bungeecord not working with build 1388

### ISSUE THREAD

**Issue by alicheek** [gamerforEA/Cauldron-Reloaded#18]
10:30:06 [INFO] [/107.136.197.231:1265] <-> InitialHandler has connected
10:30:11 [INFO] [/107.136.197.231:1266] <-> InitialHandler has connected
10:30:13 [INFO] [/107.136.197.231:1267] <-> InitialHandler has connected
10:30:13 [INFO] [/107.136.197.231:1268] <-> InitialHandler has connected
10:30:14 [INFO] [Kid_Cool123] <-> ServerConnector [sky1] has connected
10:30:33 [INFO] [/47.55.79.111:64655] <-> InitialHandler has connected
10:30:40 [INFO] [/47.55.79.111:64658] <-> InitialHandler has connected
10:30:44 [INFO] [/47.55.79.111:64659] <-> InitialHandler has connected
10:30:45 [INFO] [IraqiMilitant] <-> ServerConnector [inf1] has connected
10:30:47 [INFO] [/190.108.213.110:51236] <-> InitialHandler has connected
10:30:48 [SEVERE] [IraqiMilitant] <-> DownstreamBridge <-> [inf1] - encountered exception
io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException: -26
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:280)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -26
    at net.md_5.bungee.protocol.Protocol$DirectionData.hasPacket(Protocol.java:125)
    at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:29)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249)
    ... 17 more

other builds of cauldron seem to work fine but this one doesnt for some reason

**Comment by spannerman79** [comment]
Duplicate of #15 perhaps

**Comment by jburrows82** [comment]
This isn't a Cauldron error, please close this issue. This is a user error. Check the referenced issue and downgrade to a compatible framework.

**Comment by alicheek** [comment]
It isnt a cauldron error your right its a cofh issue
