### ISSUE TITLE
need a rcon fix

### ISSUE THREAD

**Issue by 008** [gamerforEA/Cauldron-Reloaded#5]
plz fix rcon

12:01:51 INFO]: Rcon connection from: /xxxxxxxx
[12:01:51 ERROR]: Exception whilst parsing RCON input
java.lang.NullPointerException
        at net.minecraft.network.rcon.RConThreadClient.run(RConThreadClient.java:53) [oz.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_67]

**Comment by spannerman79** [comment]
Update your Java to at least 1.7.0_75 if not Java 8

**Comment by 008** [comment]
but if i have java 8 ?

**Comment by spannerman79** [comment]
You can clearly see your running cauldron with Java 7 Update 67 - its in the error snip you provided

**Comment by gamerforEA** [comment]
Latest build with RCon fix: https://github.com/gamerforEA/Cauldron-Reloaded/releases/tag/1.1370.1.0-FixedRCon
